Homework 2: Evgeni Kuleuski
belovmd/it-academy-python-autumn pull request #18
Opened 2019-10-02 07:00 UTC by KuIibin

2019-10-05 20:16 UTC, belovmd requested changes
Thank you for your work. 
Please address these issues

2019-10-05 20:16 UTC, belovmd commented on Homework2.py
> +all = l * k
all is built-in function and it seems to be bad name for variable

2019-10-05 20:16 UTC, belovmd commented on Homework2.py
> +    if 5 < element < 25:
this code contradicts with task description: if we should print numbers less than 5 this line isn't correct. If this line is correct we should fix description

2019-10-05 20:16 UTC, belovmd commented on Homework2.py
> +        stack.append(element)
```suggestion
[element for element in a if element in b]
```

2019-10-05 20:16 UTC, belovmd commented on Homework2.py
> +if a_int == a_int[::-1]:
Please don't use strings in this task

2019-10-07 22:06 UTC, KuIibin commented
all notes taken into account

2019-10-11 20:42 UTC, belovmd reviewed
8

2019-10-11 20:42 UTC, closed without merging